# Generated by jeweler
# DO NOT EDIT THIS FILE
# Instead, edit Jeweler::Tasks in Rakefile, and run `rake gemspec`
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{ruby-wsd}
  s.version = "0.0.4"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Jorge Cal\303\241s Lozano"]
  s.date = %q{2009-10-10}
  s.default_executable = %q{wsd}
  s.description = %q{Ruby bindings for http://www.websequencediagrams.com}
  s.email = %q{calas@qvitta.net}
  s.executables = ["wsd"]
  s.extra_rdoc_files = [
    "README.rdoc"
  ]
  s.files = [
    ".gitignore",
     "CHANGELOG",
     "Manifest",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "bin/wsd",
     "lib/wsd.rb"
  ]
  s.homepage = %q{http://github.com/calas/ruby-wsd}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{Web Sequence Digrams from Ruby}

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end
